os:
  - linux
  - osx

language: python

python:
  - 2.7
  # - 3.4

cache:
  - directories:
    - /tmp

# osx_image: xcode8.2

# compiler:
#   - clang

before_install:
  # - wget http://releases.llvm.org/3.9.0/clang+llvm-3.9.0-x86_64-apple-darwin.tar.xz
  - wget http://releases.llvm.org/3.9.1/clang+llvm-3.9.1-x86_64-linux-gnu-ubuntu-14.04.tar.xz --directory-prefix=/tmp
  - tar xpf /tmp/clang+llvm-3.9.1-x86_64-linux-gnu-ubuntu-14.04.tar.xz -C /tmp
  - export PATH=/tmp//tmp/clang+llvm-3.9.1-x86_64-linux-gnu-ubuntu-14.04/bin:$PATH
  # - |
  #     if [[ -n "$PYENV_VERSION" ]]; then
  #       wget https://github.com/praekeltfoundation/travis-pyenv/releases/download/0.3.0/setup-pyenv.sh
  #       source setup-pyenv.sh
  #     fi

script:
  - clang-3.9 --version
  - python --version
  - bash run-tests.sh
