language: cpp

sudo: required

compiler:
  - clang

install:
  - sudo apt-get update
  - sudo apt-get install libclang-dev
  - sudo pip install clang

script:
  - clang --version
  - bash run-tests.sh
