os:
  - linux
  - osx

language: cpp

env:
  - PYENV_VERSION='2.7.13' PYENV_VERSION_STRING='Python 2.7.13'
  - PYENV_VERSION='3.4'

cache:
  - pip
  - directories:
    - $HOME/.pyenv_cache

osx_image: xcode8.2

compiler:
  - clang

before_install:
  - |
      if [[ -n "$PYENV_VERSION" ]]; then
        wget https://github.com/praekeltfoundation/travis-pyenv/releases/download/0.3.0/setup-pyenv.sh
        source setup-pyenv.sh
      fi

script:
  - clang --version
  - bash run-tests.sh
