language: go

os:
  - linux
  - osx

env:
  - CLANG=3.9

matrix:
  include:
    - env: CLANG=3.8
      os: linux
    - env: CLANG=3.7
      os: linux
    - env: CLANG=3.6
      os: linux
    - env: CLANG=3.4
      os: linux

before_install:
  - |
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt-add-repository "deb http://apt.llvm.org/precise/ llvm-toolchain-precise-$CLANG main"
        sudo apt-get update
        sudo apt-cache search clang
        sudo apt-get install -f -y --force-yes clang-$CLANG lldb-$CLANG
      fi

  - |
      if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        rvm get head
      fi

script:
  - . ./.travis.gofmt.sh

  # Run the unit tests first
  - |
      set -e
      echo "" > coverage.txt

      go test -tags=integration -race -coverprofile=profile.out -coverpkg ./...
      if [ -f profile.out ]; then
        cat profile.out >> coverage.txt
        rm profile.out
      fi

  # These steps are from the README to verify it can be installed and run as
  # documented.
  - cd /tmp
  - export C2GO=$GOPATH/src/github.com/elliotchance/c2go
  - c2go $C2GO/tests/prime.c > prime.go
  - go run prime.go
  - cd -

after_success:
  - include_cov=coverage.txt bash <(curl -s https://codecov.io/bash)
