os:
  - linux
  - osx

language: cpp

osx_image: xcode8.2

compiler:
  - clang

script:
  - clang --version
  - clang -Xclang -ast-dump -fsyntax-only tests/argv.c | python ast2json.py
  - bash run-tests.sh
