language: go

go:
  - 1.7

os:
  - linux
  - osx

env:
  - CLANG=3.9

matrix:
  include:
    - env: CLANG=3.8
      os: linux
    - env: CLANG=3.7
      os: linux
    - env: CLANG=3.6
      os: linux
    - env: CLANG=3.4
      os: linux

before_install:
  - |
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt-add-repository "deb http://apt.llvm.org/precise/ llvm-toolchain-precise-$CLANG main"
        sudo apt-get update
        sudo apt-cache search clang
        sudo apt-get install -f -y --force-yes clang-$CLANG lldb-$CLANG
      fi

script:
  # Run the unit tests first
  - |
      set -e
      echo "" > coverage.txt

      for d in $(go list ./... | grep -v vendor); do
          go test -race -coverprofile=profile.out -covermode=atomic $d
          if [ -f profile.out ]; then
              cat profile.out >> coverage.txt
              rm profile.out
          fi
      done

  # Now run the integration tests.
  - |
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        CLANG_BIN=clang-$CLANG bash run-tests.sh
      else
        bash run-tests.sh
      fi

  # These steps are from the README to verify it can be installed and run as
  # documented.
  - cd /tmp
  - export C2GO=$GOPATH/src/github.com/elliotchance/c2go
  - c2go $C2GO/tests/hello-world.c > hello-world.go
  - go run hello-world.go

after_success:
  - include_cov=coverage.txt bash <(curl -s https://codecov.io/bash)
