language: generic

os:
  - linux
  - osx

env:
  - PYENV_VERSION=2.7.13 CLANG=3.9
  - PYENV_VERSION=3.4.6 CLANG=3.9

matrix:
  include:
    - env: PYENV_VERSION=3.4.6 CLANG=3.8
      os: linux

cache:
  - pip
  - directories:
    - $HOME/.pyenv_cache

before_install:
  - |
      if [[ -n "$PYENV_VERSION" ]]; then
        wget https://github.com/praekeltfoundation/travis-pyenv/releases/download/0.3.0/setup-pyenv.sh
        source setup-pyenv.sh
      fi
  - |
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y --force-yes
        sudo apt-add-repository "deb http://apt.llvm.org/precise/ llvm-toolchain-precise-$CLANG main"
        sudo apt-get update
        sudo apt-cache search clang
        sudo apt-get -f install clang-$CLANG lldb-$CLANG
      fi

script:
  - |
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        CLANG_BIN=clang-$CLANG bash run-tests.sh
      else
        bash run-tests.sh
      fi
