sudo: required

language: cpp

os: osx
osx_image: xcode8.2

compiler:
  - clang

install:
  - sudo brew install llvm --with-clang --with-python --with-lld
  - sudo pip install clang

script:
  - clang --version
  - bash run-tests.sh
